version: "3.9"

networks:
  webapp:


services:
  web:
    image: nginx:stable-alpine
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
      - "./../app.:/app"
      - "./nginx/logs:/var/logs/nginx"
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - webapp
  app:
    image: bitnami/php-fpm:8.1
    restart: unless-stopped
    volumes:
      - "./../app:/app"
    working_dir: "/app"
    depends_on:
      - mysql
    networks:
      - webapp
  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: dev
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3307:3306"
    networks:
      - webapp
